config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  resource :year, only: [:show, :create, :update] do
    resource :dues, only: [:edit, :update]
    resources :funds, only: [:create, :edit, :update]
    resources :potential_meeting_times, only: [:create, :edit, :update]
  end

  resources :members, only: [:create, :edit, :update]
  resources :questionaire_deliveries, only: [:create]

  resources :questionaires, only: [:show, :update], param: :token do
    resource :payment, only: [:new, :create]
  end
end

app/models/year.rb
class Year < ApplicationRecord
  validates :calendar_year, uniqueness: true
  validate :next_task_is_known

  has_many :funds
  has_many :questionaires

  def next_task=(new_task)
    super(new_task.class)
  end

  def next_task
    type = read_attribute(:next_task)
    type && type.constantize.new
  end

  private

  def next_task_is_known
    if known_task_classes.exclude?(next_task.class)
      errors.add(:next_task, "is not a known task")
    end
  end

  def known_task_classes
    [
      ReviewDues,
      ReviewMembers,
      StartYear,
      ReviewFunds,
      AddPotentialMeetingTimes,
      ManageQuestionaires
    ]
  end
end

app/controllers/years_controller.rb
class YearsController < ApplicationController
  include Authenticable

  def show
    year = current_year || new_year
    next_task = year.next_task
    render next_task.template, locals: next_task.template_data
  end

  def create
    YearNavigator.new(year: new_year).progress
    redirect_to year_path
  end

  def update
    YearNavigator.new(year: current_year).progress
    redirect_to year_path
  end

  private

  def current_year
    CurrentYear.find
  end

  def new_year
    Year.new(
      next_task: StartYear.new,
      calendar_year: Date.current.year
    )
  end
end

app/views/years/add_potential_meeting_times.html.erb
<h1>Add Potential Meeting Dates</h1>

<table>
  <% potential_meeting_times.each do |potential_meeting_time| %>
    <tr>
      <td><%= potential_meeting_time.strftime("%B %-d") %></td>
      <td><%= potential_meeting_time.strftime("%-l:00 %p %Z") %></td>
      <td>
        <%= link_to "Edit",
          edit_year_potential_meeting_time_path(potential_meeting_time.to_i) %>
      </td>
    </tr>
  <% end %>
</table>

<%= form_with model: new_potential_meeting_time, url: year_potential_meeting_times_path do |form| %>
  <table>
    <tr>
      <td>
        <%= select_month new_potential_meeting_time,
          prefix: :potential_meeting_time,
          field_name: :month
        %>
      </td>
      <td>
        <%= select_day new_potential_meeting_time,
          prefix: :potential_meeting_time,
          field_name: :day
        %>
      </td>
      <td>
        <%= select_hour new_potential_meeting_time,
          ampm: true,
          prefix: :potential_meeting_time,
          field_name: :hour
        %>
      </td>
      <td>
        <%= form.time_zone_select :time_zone,
          ActiveSupport::TimeZone.us_zones
        %>
      </td>
      <td><%= form.submit "Add Potential Meeting Time" %></td>
    </tr>
  </table>
<% end %>

<%= link_to "Next", year_path, method: :put, remote: true %>

app/views/years/manage_questionaires.html.erb
<h1>Manage Questionaires</h1>

<table>
  <% questionaires.each do |questionaire| %>
    <tr>
      <td><%= questionaire.member_name %></td>
      <td><%= questionaire.current_status %></td>
      <td>
        <%= button_to "Send",
          questionaire_deliveries_path(questionaire_id: questionaire.id),
          remote: true
        %>
      </td>
    </tr>
  <% end %>
</table>

app/views/years/review_dues.html.erb
<h1>Review Dues</h1>

<%= number_to_currency(dues.amount_dollars) %> paid annualy

<%= link_to "Edit dues", edit_year_dues_path %>
<%= link_to "Next", year_path, method: :put, remote: true %>

app/views/years/review_funds.html.erb
<h1>Review Funds</h1>

<table>
  <tr>
    <th>Fund Name</th>
    <th>Contribution Amount</th>
  </tr>

  <% funds.each do |fund| %>
    <tr>
      <td><%= fund.name %></td>
      <td><%= number_to_currency(fund.contribution_amount_dollars) %></td>
      <td><%= link_to "Edit", edit_year_fund_path(fund) %></td>
    </tr>
  <% end %>
</table>

<%= form_with model: [:year, Fund.new] do |form| %>
  <table>
    <tr>
      <td><%= form.text_field :name, placeholder: "Name" %></td>
      <td>
        <%= form.number_field :contribution_amount_dollars, step: "0.01" %>
      </td>
      <td><%= form.submit "Add Fund" %></td>
    </tr>
  </table>
<% end %>

<%= link_to "Next", year_path, method: :put, remote: true %>

app/views/years/review_members.html.erb
<h1>Review Members</h1>

<table>
  <% members.each do |member| %>
    <tr>
      <td><%= member.name %></td>
      <td><%= member.email %></td>
      <td><%= link_to "Edit", edit_member_path(member) %></td>
    </tr>
  <% end %>
</table>

<%= form_with model: Member.new do |form| %>
  <table>
    <tr>
      <td><%= form.text_field :name, placeholder: "Name" %></td>
      <td><%= form.email_field :email, placeholder: "Email" %></td>
      <td><%= form.submit "Add Member" %></td>
    </tr>
  </table>
<% end %>

<%= link_to "Next", year_path, method: :put, remote: true %>

app/views/years/start_year.html.erb
<%= link_to "Start New Year", year_path, method: :post, remote: true %>